"""
Generated by 'esmerald createapp' using Esmerald 3.2.3.
"""
from esmerald import Include, Gateway
from .controllers import AccountController

route_patterns = [
    Gateway(
        path="/users",
        handler=AccountController,
    )
]
