"""
Esmerald settings for config project.

Generated by 'esmerald createproject' using Esmerald 3.2.3.
"""
from functools import cached_property
from typing import Optional

from edgy import Database, Registry
from esmerald.conf.enums import EnvironmentType
from esmerald.conf.global_settings import EsmeraldAPISettings
from esmerald_simple_jwt.config import SimpleJWT


class AppSettings(EsmeraldAPISettings):
    app_name: str = "My application in production mode."
    title: str = "My config"
    environment: Optional[str] = EnvironmentType.PRODUCTION
    secret_key: str = "esmerald-insecure-ij@!ya!(e4x#koc)g+e)0)%5c#1m199p!o=4$*zb+v&amp;(2jgyww"
    auth_user_model: str = "admin_test.src.apps.account.models.User"

    class Config:
        env_file = '.env'

    @property
    def url(self) -> str:
        return "sqlite+aiosqlite:///example.db"

    @cached_property
    def db_connection(self) -> tuple[Database, Registry]:
        database = Database(self.url)
        return database, Registry(database=database)

    @property
    def simple_jwt(self) -> SimpleJWT:
        from contrib.auth.backends import BackendAuthentication, RefreshAuthentication

        return SimpleJWT(
            signing_key=self.secret_key,
            backend_authentication=BackendAuthentication,
            backend_refresh=RefreshAuthentication,
        )
